Repository cardstack/boxel, pull requests merged in 2023-05, with the labels that each got.

#317 docs: Add details on computed fields
  docs/computed-fields.md
  docs/indexing.md
Labels: documentation

#331 Adopt volta
  .github/actions/deploy-boxel-host/action.yml
  .github/actions/deploy-ember-preview/action.yml
  .github/actions/deploy-realm-server/action.yml
  .github/workflows/ci.yaml
  .github/workflows/pr-boxel-host.yml
  README.md
  package.json
  packages/boxel-motion-demo-app/package.json
  packages/boxel-motion-test-app/package.json
  packages/boxel-motion/package.json
  packages/boxel-ui/package.json
  packages/host/package.json
  packages/host/tests/helpers/index.gts
  packages/matrix/package.json
  packages/realm-server/package.json
  packages/worker/package.json
Labels: chore

#329 Add /_info route to realm server
  .eslintrc.js
  packages/host/tests/integration/realm-test.ts
  packages/host/tests/integration/search-index-test.ts
  packages/realm-server/tests/cards/.realm.json
  packages/realm-server/tests/realm-server-test.ts
  packages/runtime-common/realm.ts
  packages/runtime-common/router.ts
  packages/runtime-common/search-index.ts
Labels: enhancement

#339 Set VOLTA env var for deploy workflows
  .github/workflows/manual-boxel-host.yml
  .github/workflows/manual-boxel-realm-server.yml
Labels: bug

#342 Move a few things out of runtime-common that were only consumed by host
  packages/host/tests/helpers/index.gts
  packages/host/tests/helpers/stream.ts
  packages/host/tests/unit/diffing-test.ts
  packages/realm-server/fastboot-from-deployed.ts
  packages/realm-server/fastboot.ts
  packages/runtime-common/diff-entries.ts
  packages/runtime-common/index.ts
  packages/runtime-common/realm.ts
  packages/runtime-common/search-index.ts
  packages/runtime-common/stream.ts
Labels: chore

#348 ci: Change lint to proceed despite failures
  .github/workflows/ci.yaml
Labels: enhancement

#360 Clicking the exposed header of a "buried" card closes the cards above it
  packages/boxel-ui/addon/helpers/truth-helpers.ts
  packages/host/app/components/operator-mode.gts
  packages/host/app/styles/app.css
  packages/host/tests/integration/components/operator-mode-test.gts
  pnpm-lock.yaml
Labels: enhancement

#365 Update to pnpm 8
  package.json
  packages/boxel-motion/package.json
  packages/realm-server/Dockerfile
  pnpm-lock.yaml
Labels: chore

#367 ci: Add override to always lint packages/matrix
  .github/workflows/ci.yaml
Labels: bug
