Repository cardstack/boxel, pull requests merged in 2023-10, with the labels that each got.

#724 host: Extract RealmIcon component
  packages/host/app/components/editor/recent-files.gts
  packages/host/app/components/operator-mode/card-preview-panel.gts
  packages/host/app/components/operator-mode/card-schema-editor.gts
  packages/host/app/components/operator-mode/card-url-bar.gts
  packages/host/app/components/operator-mode/code-mode.gts
  packages/host/app/components/operator-mode/definition-container/base.gts
  packages/host/app/components/operator-mode/realm-icon.gts
  packages/host/app/components/operator-mode/stack-item.gts
  packages/host/tests/acceptance/code-mode-test.ts
Labels: bug

#725 base: Add type imports for Ember packages
  packages/base/types/@cardstack/base/index.d.ts
  packages/host/app/lib/externals.ts
Labels: bug

#695 host: Add more realm awareness to code mode
  packages/host/app/components/editor/directory.gts
  packages/host/app/components/editor/file-tree.gts
  packages/host/app/components/editor/go.gts
  packages/host/app/components/editor/recent-files.gts
  packages/host/app/components/operator-mode/card-url-bar.gts
  packages/host/app/components/operator-mode/code-mode.gts
  packages/host/app/components/operator-mode/realm-info-provider.gts
  packages/host/app/resources/directory.ts
  packages/host/app/services/operator-mode-state-service.ts
  packages/host/app/services/realm-info-service.ts
  packages/host/app/services/recent-files-service.ts
  packages/host/tests/acceptance/code-mode-test.ts
  packages/host/tests/acceptance/operator-mode-test.ts
Labels: bug

#713 host: Add custom assertion for operator mode parameters
  packages/host/tests/acceptance/operator-mode-test.ts
  packages/host/tests/helpers/operator-mode-parameters-match.ts
  packages/host/tests/test-helper.js
Labels: enhancement

#746 host: Fix deployment command
  package.json
Labels: bug

#706 Update Embroider dependencies
  package.json
  packages/base/package.json
  packages/boxel-motion-demo-app/package.json
  packages/boxel-motion-test-app/package.json
  packages/boxel-motion/package.json
  packages/boxel-ui/addon/package.json
  packages/boxel-ui/test-app/package.json
  packages/host/package.json
  packages/runtime-common/package.json
  pnpm-lock.yaml
Labels: chore

#745 Fix prettier config
  .prettierrc.js
  .vscode/settings.json
  package.json
  packages/ai-bot/promptfooconfig.yaml
  packages/ai-bot/tests/resources/chats/!EHSrJvmtuZtpNeKXsv:localhost.json
  packages/base/package.json
  packages/boxel-motion-demo-app/package.json
  packages/boxel-motion-test-app/package.json
  packages/boxel-motion/addon/components/animation-context.gts
  packages/boxel-motion/package.json
  packages/boxel-ui/README.md
  packages/boxel-ui/addon/babel.config.json
  packages/boxel-ui/addon/package.json
  packages/boxel-ui/addon/src/components/dropdown/trigger/index.gts
  packages/boxel-ui/addon/src/components/field-container/index.gts
  packages/boxel-ui/addon/src/components/loading-indicator/index.gts
  packages/boxel-ui/addon/src/components/menu/index.gts
  packages/boxel-ui/addon/tsconfig.json
  packages/boxel-ui/test-app/package.json
  packages/boxel-ui/test-app/tsconfig.json
  packages/drafts-realm/ContactCard/1.json
  packages/drafts-realm/Person/1.json
  packages/drafts-realm/post.gts
  packages/drafts-realm/tsconfig.json
  packages/drafts-realm/utils/resources/metamask.gts
  packages/host/app/components/operator-mode/detail-panel-selector.gts
  packages/host/app/components/operator-mode/schema-editor-column.gts
  packages/host/app/templates/index.hbs
  packages/host/package.json
  packages/host/tsconfig.json
  packages/matrix/docker/synapse/dev/homeserver.yaml
  packages/matrix/docker/synapse/test-without-registration-token/homeserver.yaml
  packages/matrix/docker/synapse/test/homeserver.yaml
  packages/realm-server/package.json
  packages/realm-server/tsconfig.json
  packages/runtime-common/package.json
  pnpm-lock.yaml
  vendor/ember-template-imports/package.json
  vendor/transform-modules-amd-plugin/package.json
Labels: bug

#744 Additional docs updates for boxel-ui addon changes
  README.md
  packages/boxel-ui/README.md
Labels: docs

#727 host: Add vertical resizing in left code mode column
  packages/boxel-ui/addon/src/components/resizable-panel-group/index.gts
  packages/boxel-ui/addon/src/components/resizable-panel-group/panel.gts
  packages/boxel-ui/addon/src/components/resizable-panel-group/usage.gts
  packages/host/app/components/operator-mode/code-mode.gts
Labels: enhancement

#754 ui: Hide resize handles in narrow panels
  packages/boxel-ui/addon/src/components/resizable-panel-group/index.gts
  packages/boxel-ui/addon/src/components/resizable-panel-group/panel.gts
Labels: bug

#756 ui: Change resize handle colours to match design
  packages/boxel-ui/addon/src/components/resizable-panel-group/panel.gts
  packages/boxel-ui/addon/src/components/resizable-panel-group/usage.gts
Labels: bug

#755 Break up large acceptance test files into more focused ones
  packages/host/tests/acceptance/code-submode-test.ts
  packages/host/tests/acceptance/code-submode/editor-test.ts
  packages/host/tests/acceptance/code-submode/file-tree-test.ts
  packages/host/tests/acceptance/code-submode/inspector-test.ts
  packages/host/tests/acceptance/code-submode/recent-files-test.ts
  packages/host/tests/acceptance/code-submode/schema-editor-test.ts
  packages/host/tests/acceptance/interact-submode-test.ts
  packages/host/tests/acceptance/operator-mode-test.ts
Labels: chore

#748 host: Extract Pill component
  packages/boxel-ui/addon/src/styles/variables.css
  packages/host/app/components/operator-mode/add-field-modal.gts
  packages/host/app/components/operator-mode/card-schema-editor.gts
  packages/host/app/components/pill.gts
  packages/host/tests/acceptance/code-submode/schema-editor-test.ts
Labels: enhancement

#765 host: Fix recent files truncation test flakiness
  packages/host/tests/acceptance/code-submode/recent-files-test.ts
Labels: bug

#763 ui: Fix how resizable panel handles are hidden
  packages/boxel-ui/addon/src/components/resizable-panel-group/index.gts
  packages/boxel-ui/addon/src/components/resizable-panel-group/panel.gts
Labels: bug

#774 ui: Fix direction of resize arrow when collapsed
  packages/boxel-ui/addon/src/components/resizable-panel-group/panel.gts
Labels: bug

#775 ui: Fix ResizablePanelGroup in Firefox
  packages/boxel-ui/addon/src/components/resizable-panel-group/index.gts
Labels: bug

#776 Display default cursor on modal
  packages/boxel-ui/addon/src/components/modal/index.gts
Labels: bug

#772 host: Fix overlapping double icons in pill
  packages/host/app/components/operator-mode/card-schema-editor.gts
  packages/host/app/components/pill.gts
Labels: bug

#783 host: Rename showBrowser to isFileTreeShowing
  packages/host/app/components/operator-mode/code-submode.gts
Labels: enhancement

#785 host: Add radius transition for submode animation
  packages/host/app/components/submode-switcher.gts
Labels: bug
