Repository cardstack/boxel, pull requests merged in 2023-08, with the labels that each got.

#511 Update to Ember Concurrency 3.1.0
  package.json
  packages/base/package.json
  packages/boxel-motion-demo-app/package.json
  packages/host/package.json
  pnpm-lock.yaml
Labels: chore

#486 runtime: Remove static loader APIs
  packages/base/card-api.gts
  packages/base/catalog-entry.gts
  packages/base/room.gts
  packages/host/app/app.ts
  packages/host/app/lib/current-run.ts
  packages/host/app/lib/externals.ts
  packages/host/app/lib/matrix-handlers/index.ts
  packages/host/app/lib/matrix-handlers/timeline.ts
  packages/host/app/services/card-service.ts
  packages/host/app/services/loader-service.ts
  packages/host/tests/acceptance/basic-test.ts
  packages/host/tests/acceptance/operator-mode-test.ts
  packages/host/tests/helpers/index.gts
  packages/host/tests/helpers/render-component.ts
  packages/host/tests/integration/card-prerender-test.gts
  packages/host/tests/integration/components/card-basics-test.gts
  packages/host/tests/integration/components/card-editor-test.gts
  packages/host/tests/integration/components/catalog-entry-editor-test.gts
  packages/host/tests/integration/components/computed-test.gts
  packages/host/tests/integration/components/file-tree-test.gts
  packages/host/tests/integration/components/go-test.gts
  packages/host/tests/integration/components/operator-mode-test.gts
  packages/host/tests/integration/components/preview-test.gts
  packages/host/tests/integration/components/schema-test.gts
  packages/host/tests/integration/components/serialization-test.gts
  packages/host/tests/integration/components/text-input-filter-test.gts
  packages/host/tests/integration/realm-test.ts
  packages/host/tests/integration/search-index-test.ts
  packages/realm-server/lib/externals.ts
  packages/realm-server/main.ts
  packages/realm-server/middleware/index.ts
  packages/realm-server/server.ts
  packages/realm-server/tests/helpers/index.ts
  packages/realm-server/tests/indexing-test.ts
  packages/realm-server/tests/loader-test.ts
  packages/realm-server/tests/module-syntax-test.ts
  packages/realm-server/tests/realm-server-test.ts
  packages/runtime-common/card-ref.ts
  packages/runtime-common/loader.ts
  packages/runtime-common/realm.ts
  packages/runtime-common/search-index.ts
Labels: enhancement

#522 Update to Typescript 5
  package.json
  packages/ai-bot/package.json
  packages/boxel-motion-demo-app/package.json
  packages/boxel-motion-test-app/package.json
  packages/boxel-motion/addon/utils/measurement.ts
  packages/boxel-motion/package.json
  packages/boxel-ui/package.json
  packages/host/package.json
  packages/matrix/package.json
  packages/realm-server/package.json
  pnpm-lock.yaml
  vendor/ember-template-imports/package.json
Labels: enhancement, chore

#524 host: Add branch name truncation for previews
  .github/actions/deploy-ember-preview/action.yml
Labels: bug

#518 host: Fix realm URLs for preview deployments
  .github/workflows/build-host.yml
Labels: bug

#469 runtime: Add support for scoped CSS
  packages/host/tests/acceptance/basic-test.ts
  packages/host/tests/integration/card-prerender-test.gts
  packages/host/tests/integration/realm-test.ts
  packages/host/tests/integration/search-index-test.ts
  packages/realm-server/tests/indexing-test.ts
  packages/realm-server/tests/realm-server-test.ts
  packages/runtime-common/helpers/strip-scoped-css-attributes.ts
  packages/runtime-common/helpers/strip-scoped-css-glimmer-attributes.ts
  packages/runtime-common/loader.ts
  packages/runtime-common/package.json
  packages/runtime-common/realm.ts
  pnpm-lock.yaml
Labels: enhancement

#543 Test fixes
  packages/host/tests/integration/components/operator-mode-test.gts
Labels: chore

#537 Convert cards to use scoped CSS
  packages/base/cards-grid.gts
  packages/base/catalog-entry.gts
  packages/base/contains-many-component.gts
  packages/base/default-card-component.gts
  packages/base/field-component.gts
  packages/base/links-to-editor.gts
  packages/base/links-to-many-component.gts
  packages/boxel-ui/addon/components/add-button/index.gts
  packages/boxel-ui/addon/components/add-button/usage.gts
  packages/boxel-ui/addon/components/grid-container/index.gts
  packages/boxel-ui/addon/components/grid-container/usage.gts
  packages/boxel-ui/addon/index.ts
  packages/boxel-ui/package.json
  packages/boxel-ui/tests/acceptance/index-test.ts
  packages/boxel-ui/tests/dummy/app/controllers/index.js
  packages/drafts-realm/asset.gts
  packages/drafts-realm/author.gts
  packages/drafts-realm/claim-list.gts
  packages/drafts-realm/claim.gts
  packages/drafts-realm/friend.gts
  packages/drafts-realm/friends.gts
  packages/drafts-realm/invoice-packet.gts
  packages/drafts-realm/person.gts
  packages/drafts-realm/pet-person.gts
  packages/drafts-realm/pet.gts
  packages/drafts-realm/transaction.gts
  packages/drafts-realm/vendor.gts
  packages/host/app/components/editor/file-tree.gts
  packages/host/app/components/operator-mode/stack.gts
  packages/host/app/styles/app.css
  packages/host/package.json
  packages/host/tests/cards/pet-person.gts
  packages/host/tests/integration/search-index-test.ts
  packages/published-realm/person.gts
  packages/published-realm/pet.gts
  packages/runtime-common/helpers/strip-scoped-css-attributes.ts
  packages/runtime-common/helpers/strip-scoped-css-glimmer-attributes.ts
  packages/runtime-common/loader.ts
  packages/runtime-common/package.json
  pnpm-lock.yaml
Labels: enhancement

#546 host: Fix test setup from scoped CSS import
  packages/host/tests/integration/components/go-test.gts
Labels: bug, chore

#552 host: Add delay for Percy index card snapshot
  packages/host/tests/acceptance/operator-mode-test.ts
Labels: bug

#566 host: Fix more realm URLs
  .github/workflows/pr-boxel-host.yml
  README.md
Labels: bug

#551 host: Add Percy for code route
  packages/host/app/modifiers/monaco.ts
  packages/host/tests/acceptance/basic-test.ts
Labels: enhancement

#553 saveCardDocument is sending a post when it shud be a patch
  packages/host/app/components/editor/go.gts
  packages/host/app/services/card-service.ts
Labels: bug

#575 host: Add Percy delay for card rendering
  packages/host/tests/acceptance/basic-test.ts
Labels: bug, chore

#567 host: Add recent files listing in code mode
  packages/host/app/components/editor/go.gts
  packages/host/app/components/editor/recent-files.gts
  packages/host/app/controllers/code.ts
  packages/host/app/services/code-service.ts
  packages/host/package.json
  packages/host/tests/acceptance/basic-test.ts
  packages/host/tests/integration/components/file-tree-test.gts
  packages/host/tests/integration/components/go-test.gts
  packages/host/tests/integration/components/schema-test.gts
  pnpm-lock.yaml
Labels: enhancement

#587 Fix issue where recent cards are halfway down the screen from search results in an opened SearchSheet
  packages/host/app/components/search-sheet/index.gts
Labels: bug

#588 Fix bug where search sheet does not open card when no stacks present
  packages/host/app/components/operator-mode/container.gts
  packages/host/tests/acceptance/operator-mode-test.ts
Labels: bug
