Repository cardstack/boxel, pull requests merged in 2024-01, with the labels that each got.

#943 Fix linting of gts files in host package
  packages/host/app/components/card-catalog/index.gts
  packages/host/app/components/card-catalog/item.gts
  packages/host/app/components/card-catalog/modal.gts
  packages/host/app/components/card-catalog/results-header.gts
  packages/host/app/components/card-error.gts
  packages/host/app/components/card-prerender.gts
  packages/host/app/components/create-card-modal.gts
  packages/host/app/components/editor/file-tree.gts
  packages/host/app/components/format-picker.gts
  packages/host/app/components/matrix/room.gts
  packages/host/app/components/matrix/rooms-manager.gts
  packages/host/app/components/matrix/user-profile.gts
  packages/host/app/components/operator-mode/binary-file-info.gts
  packages/host/app/components/operator-mode/card-preview-panel.gts
  packages/host/app/components/operator-mode/card-schema-editor.gts
  packages/host/app/components/operator-mode/card-url-bar.gts
  packages/host/app/components/operator-mode/code-editor.gts
  packages/host/app/components/operator-mode/code-submode.gts
  packages/host/app/components/operator-mode/code-submode/inner-container.gts
  packages/host/app/components/operator-mode/code-submode/schema-editor.gts
  packages/host/app/components/operator-mode/container.gts
  packages/host/app/components/operator-mode/context-menu-button.gts
  packages/host/app/components/operator-mode/copy-button.gts
  packages/host/app/components/operator-mode/create-file-modal.gts
  packages/host/app/components/operator-mode/definition-container/base.gts
  packages/host/app/components/operator-mode/definition-container/clickable.gts
  packages/host/app/components/operator-mode/detail-panel.gts
  packages/host/app/components/operator-mode/interact-submode.gts
  packages/host/app/components/operator-mode/new-file-button.gts
  packages/host/app/components/operator-mode/overlay-item-header.gts
  packages/host/app/components/operator-mode/overlays.gts
  packages/host/app/components/operator-mode/stack-item.gts
  packages/host/app/components/operator-mode/stack.gts
  packages/host/app/components/operator-mode/submode-layout.gts
  packages/host/app/components/realm-dropdown.gts
  packages/host/app/components/search-sheet/index.gts
  packages/host/package.json
  packages/host/tests/helpers/index.gts
  packages/host/tests/integration/components/card-basics-test.gts
  packages/host/tests/integration/components/card-copy-test.gts
Labels: internal

#951 host: Remove old chat session/profile management
  packages/host/app/components/matrix/user-profile.gts
  packages/matrix/helpers/index.ts
  packages/matrix/tests/login.spec.ts
Labels: bug

#950 matrix: Fix documentation on running tests
  README.md
Labels: bug

#949 ai-bot: Add setup improvements
  packages/ai-bot/README.md
  packages/matrix/package.json
  packages/matrix/scripts/register-test-admin.ts
  packages/matrix/scripts/register-test-token.ts
  packages/matrix/scripts/register-test-user.ts
Labels: enhancement

#958 host: Fix Freestyle navigation
  packages/host/app/controllers/host-freestyle.ts
Labels: bug

#973 Fix an issue where a computed contains field would not render an atom format, only embedded
  packages/base/field-component.gts
  packages/host/tests/integration/components/card-basics-test.gts
Labels: bug

#972 Fixes an issue where New Field modal appeared without base field selected by default
  packages/host/app/components/operator-mode/create-file-modal.gts
  packages/host/tests/acceptance/code-submode/create-file-test.gts
Labels: bug

#964 Improve keyboard handling of CodeMode New file modals
  packages/host/app/components/operator-mode/create-file-modal.gts
  packages/host/app/components/operator-mode/edit-field-modal.gts
Labels: enhancement

#978 host: Change Matrix password requirements
  packages/host/app/components/matrix/forgot-password.gts
  packages/host/app/components/matrix/register-user.gts
  packages/host/app/components/operator-mode/profile/profile-settings-modal.gts
  packages/host/app/lib/matrix-utils.ts
  packages/matrix/tests/forgot-password.spec.ts
  packages/matrix/tests/profile.spec.ts
  packages/matrix/tests/registration-with-token.spec.ts
Labels: bug

#955 host: Change edit icon to reflect permissions
  packages/host/app/components/operator-mode/stack-item.gts
  packages/host/app/services/matrix-service.ts
  packages/host/app/services/sessions-service.ts
  packages/host/tests/acceptance/interact-submode-test.gts
  packages/host/tests/helpers/index.gts
  packages/host/tests/helpers/mock-sessions-service.ts
  packages/host/tests/integration/components/card-delete-test.gts
  packages/host/tests/integration/components/operator-mode-test.gts
  packages/matrix/tests/login.spec.ts
Labels: enhancement

#969 AI assistant: Past sessions list
  packages/base/room.gts
  packages/host/app/components/ai-assistant/panel-popover.gts
  packages/host/app/components/ai-assistant/panel.gts
  packages/host/app/components/ai-assistant/past-sessions.gts
  packages/host/app/components/matrix/room-list.gts
  packages/host/tests/helpers/mock-matrix-service.ts
  packages/host/tests/integration/components/operator-mode-test.gts
  packages/matrix/helpers/index.ts
  packages/matrix/tests/messages.spec.ts
  packages/matrix/tests/room-creation.spec.ts
Labels: enhancement

#994 host: Fix incorrect stacking of embedded card
  packages/host/app/components/ai-assistant/panel-popover.gts
Labels: bug

#995 ui: Move tooltips to overlay
  packages/boxel-ui/addon/src/components/tooltip/index.gts
  packages/host/tests/acceptance/code-submode/schema-editor-test.ts
Labels: bug

#986 host: Add display of Matrix registration errors
  packages/host/app/components/matrix/register-user.gts
  packages/matrix/tests/registration-with-token.spec.ts
Labels: bug

#1003 Improve layout of Past Sessions, including when there are many past sessions
  packages/host/app/components/ai-assistant/panel-popover.gts
  packages/host/app/components/ai-assistant/panel.gts
Labels: bug

#1000 host: Add display of card preview errors
  packages/host/app/components/operator-mode/code-submode.gts
  packages/host/app/resources/card-resource.ts
  packages/host/tests/acceptance/code-submode-test.ts
Labels: enhancement

#1008 host: Fix images in deployed environments
  packages/host/app/components/ai-assistant/ai-assist-icon.webp
  packages/host/app/components/ai-assistant/ai-assist-icon@2x.webp
  packages/host/app/components/ai-assistant/ai-assist-icon@3x.webp
  packages/host/app/components/ai-assistant/button.gts
  packages/host/app/components/ai-assistant/message/index.gts
  packages/host/app/components/ai-assistant/panel.gts
  packages/host/ember-cli-build.js
  packages/host/types/index.d.ts
Labels: bug
