Repository cardstack/boxel, pull requests merged in 2024-12, with the labels that each got.

#1877 tools: Fix login failure messages
  packages/vscode-boxel-tools/src/synapse-auth-provider.ts
Labels: bug

#1844 tools: Fix creation of JS, JSON, TS files
  packages/host/app/components/operator-mode/code-submode.gts
  packages/runtime-common/index-query-engine.ts
  packages/runtime-common/realm.ts
  packages/vscode-boxel-tools/src/file-system-provider.ts
Labels: bug

#1892 ci: Add more Matrix tests shards
  .github/workflows/ci.yaml
Labels: chore

#1900 host: Remove stack trace from Percy snapshots
  packages/host/app/components/operator-mode/card-error-detail.gts
Labels: bug

#1904 tools: Add publishing to Open VSX
  .github/workflows/manual-vscode-boxel-tools.yml
Labels: enhancement

#1920 ai: Add attachment for JSON parse failure
  packages/ai-bot/helpers.ts
Labels: bug

#1860 Add phone input component
  packages/boxel-ui/addon/package.json
  packages/boxel-ui/addon/src/components.ts
  packages/boxel-ui/addon/src/components/input-group/accessories/index.gts
  packages/boxel-ui/addon/src/components/phone-input/index.gts
  packages/boxel-ui/addon/src/components/phone-input/usage.gts
  packages/boxel-ui/addon/src/usage.ts
  packages/experiments-realm/CardWithContactPhoneNumber/83289456-e32b-462c-8101-010aaa62527c.json
  packages/experiments-realm/Contact/a01fc5c9-d70d-4b9c-aae4-384cf2b79b25.json
  packages/experiments-realm/ExperimentsFieldsPreview/de720f57-964b-4a09-8d52-80cd8bb4b739.json
  packages/experiments-realm/crm/contact.gts
  packages/experiments-realm/experiments_fields_preview.gts
  packages/experiments-realm/phone-number.gts
  packages/experiments-realm/phone.gts
  pnpm-lock.yaml
Labels: boxel-ui
