Repository cardstack/boxel, pull requests merged in 2024-11, with the labels that each got.

#1757 tools: Update version
  packages/vscode-boxel-tools/package.json
Labels: chore

#1779 Add error-handling to full reset script
  package.json
  packages/realm-server/package.json
  packages/realm-server/scripts/full-reset.sh
  scripts/full-reset.sh
Labels: enhancement

#1767 tools: Fix task launch in development
  .vscode/tasks.json
Labels: bug

#1826 Check if user has enough credits before responding with AI generated …
  packages/ai-bot/lib/ai-billing.ts
  packages/ai-bot/lib/matrix.ts
  packages/ai-bot/main.ts
Labels: blocked

#1852 host: Fix SVG width typo
  packages/host/app/components/matrix/payment-setup.gts
Labels: bug

#1855 Fix admin data
  packages/experiments-realm/blog-app.gts
  packages/experiments-realm/components/grid.gts
Labels: bug

#1853 Move search icon placement to always be on the LEFT
  packages/boxel-ui/addon/src/components/input/index.gts
Labels: boxel-ui
