Repository cardstack/boxel, pull requests merged in 2024-03, with the labels that each got.

#1070 host: Fix editor permissions icon to right-aligned
  packages/host/app/components/editor/file-tree.gts
Labels: bug

#1074 ai: Add Sentry
  packages/ai-bot/main.ts
  packages/ai-bot/package.json
  pnpm-lock.yaml
Labels: enhancement

#1053 realm: Add permissions support for all users
  packages/host/app/components/matrix/login.gts
  packages/host/app/components/matrix/register-user.gts
  packages/host/app/components/operator-mode/container.gts
  packages/host/app/routes/card.gts
  packages/host/app/services/loader-service.ts
  packages/host/app/services/matrix-service.ts
  packages/host/app/services/realm-info-service.ts
  packages/host/app/templates/card.gts
  packages/host/tests/acceptance/permissioned-realm-test.gts
  packages/host/tests/helpers/index.gts
  packages/host/tests/helpers/operator-mode-parameters-match.ts
  packages/realm-server/tests/permissions/permission-checker-test.ts
  packages/runtime-common/matrix-client.ts
  packages/runtime-common/realm-permission-checker.ts
  packages/runtime-common/realm.ts
  packages/runtime-common/router.ts
Labels: bug

#1081 ci: Fix Matrix URL for production previews
  .github/workflows/pr-boxel-host.yml
Labels: bug

#1088 ui: Update ember-{basic-dropdown,power-select}
  package.json
  packages/base/package.json
  packages/boxel-motion/addon/package.json
  packages/boxel-motion/test-app/package.json
  packages/boxel-ui/addon/babel.config.json
  packages/boxel-ui/addon/package.json
  packages/boxel-ui/addon/src/components/input-group/accessories/index.gts
  packages/boxel-ui/addon/src/components/input-group/index.gts
  packages/boxel-ui/addon/src/components/input-group/usage.gts
  packages/boxel-ui/addon/src/components/select/index.gts
  packages/boxel-ui/addon/src/components/select/usage.gts
  packages/boxel-ui/addon/src/types/ember-basic-dropdown/index.d.ts
  packages/boxel-ui/addon/src/types/ember-power-select/components/power-select/index.d.ts
  packages/boxel-ui/test-app/app/app.js
  packages/boxel-ui/test-app/app/index.html
  packages/boxel-ui/test-app/app/templates/index.hbs
  packages/boxel-ui/test-app/package.json
  packages/host/app/app.ts
  packages/host/app/templates/host-freestyle.gts
  packages/host/package.json
  packages/runtime-common/etc/test-fixtures.ts
  packages/runtime-common/package.json
  patches/ember-basic-dropdown@8.0.4.patch
  pnpm-lock.yaml
  vendor/ember-template-imports/package.json
  vendor/transform-modules-amd-plugin/package.json
Labels: enhancement

#1106 Keep AI Assistant button visible when panel open, in active state
  packages/boxel-ui/addon/src/components/resizable-panel-group/index.gts
  packages/boxel-ui/addon/src/components/resizable-panel-group/panel.gts
  packages/boxel-ui/addon/src/components/resizable-panel-group/usage.gts
  packages/boxel-ui/test-app/tests/integration/components/resizable-panel-group-test.gts
  packages/host/app/components/ai-assistant/ai-assist-button-active-bg.webp
  packages/host/app/components/ai-assistant/ai-assist-button-active-bg@2x.webp
  packages/host/app/components/ai-assistant/ai-assist-button-active-bg@3x.webp
  packages/host/app/components/ai-assistant/ai-assist-icon-bw.png
  packages/host/app/components/ai-assistant/ai-assist-icon-bw@2x.png
  packages/host/app/components/ai-assistant/ai-assist-icon-bw@3x.png
  packages/host/app/components/ai-assistant/button.gts
  packages/host/app/components/ai-assistant/panel.gts
  packages/host/app/components/operator-mode/stack-item.gts
  packages/host/app/components/operator-mode/submode-layout.gts
  packages/host/ember-cli-build.js
Labels: enhancement

#1117 Update work plan diagram for postgres-backed index project
  docs/indexer-work-plan.mermaid
Labels: documentation

#1111 Update dependencies in Ember packages
  package.json
  packages/base/package.json
  packages/boxel-motion/addon/package.json
  packages/boxel-motion/test-app/app/app.js
  packages/boxel-motion/test-app/app/deprecation-workflow.js
  packages/boxel-motion/test-app/package.json
  packages/boxel-ui/addon/package.json
  packages/boxel-ui/test-app/app/app.js
  packages/boxel-ui/test-app/app/deprecation-workflow.js
  packages/boxel-ui/test-app/package.json
  packages/host/app/app.ts
  packages/host/app/deprecation-workflow.js
  packages/host/package.json
  packages/realm-server/package.json
  packages/runtime-common/etc/test-fixtures.ts
  packages/runtime-common/package.json
  pnpm-lock.yaml
  vendor/ember-template-imports/package.json
  vendor/transform-modules-amd-plugin/package.json
Labels: chore

#1109 ui: Add deployments
  .github/actions/deploy-ember-preview/action.yml
  .github/workflows/deploy-ui.yml
  .github/workflows/manual-deploy.yml
  .github/workflows/pr-boxel-ui.yml
  package.json
  packages/boxel-ui/test-app/config/deploy.js
  packages/boxel-ui/test-app/package.json
  pnpm-lock.yaml
Labels: enhancement

#1110 motion: Add deployments
  .github/workflows/deploy-motion.yml
  .github/workflows/manual-deploy.yml
  .github/workflows/pr-boxel-motion.yml
  README.md
  package.json
  packages/boxel-motion/test-app/config/deploy.js
  packages/boxel-motion/test-app/package.json
  pnpm-lock.yaml
Labels: enhancement

#1123 Revert Glint dependencies to 1.3.0
  package.json
  packages/base/package.json
  packages/boxel-motion/addon/package.json
  packages/boxel-motion/test-app/package.json
  packages/boxel-ui/addon/package.json
  packages/boxel-ui/test-app/package.json
  packages/host/package.json
  pnpm-lock.yaml
Labels: bug

#1105 boxel-motion improvements
  .github/workflows/ci.yaml
  QUICKSTART.md
  README.md
  packages/boxel-motion/addon/package.json
  packages/boxel-motion/addon/rollup.config.mjs
  packages/boxel-motion/addon/src/behaviors/base.ts
  packages/boxel-motion/addon/src/behaviors/spring.ts
  packages/boxel-motion/addon/src/behaviors/static.ts
  packages/boxel-motion/addon/src/behaviors/tween.ts
  packages/boxel-motion/addon/src/behaviors/wait.ts
  packages/boxel-motion/addon/src/components/animation-context.gts
  packages/boxel-motion/addon/src/index.ts
  packages/boxel-motion/addon/src/models/orchestration.ts
  packages/boxel-motion/addon/src/models/sprite.ts
  packages/boxel-motion/addon/src/styles/addon.css
  packages/boxel-motion/addon/src/utils/generate-frames.ts
  packages/boxel-motion/test-app/app/app.js
  packages/boxel-motion/test-app/app/controllers/split-view.ts
  packages/boxel-motion/test-app/app/router.js
  packages/boxel-motion/test-app/app/styles/app.css
  packages/boxel-motion/test-app/app/templates/application.hbs
  packages/boxel-motion/test-app/app/templates/removed-sprite-interruption.hbs
  packages/boxel-motion/test-app/app/templates/split-view.hbs
  packages/boxel-motion/test-app/vendor/app.css
Labels: internal
