Repository cardstack/boxel, pull requests merged in 2024-05, with the labels that each got.

#1198 host: Add handling for Unicode in file/class names
  packages/host/app/components/card-catalog/item.gts
  packages/host/app/components/editor/recent-files.gts
  packages/host/app/components/operator-mode/card-url-bar.gts
  packages/host/app/components/operator-mode/create-file-modal.gts
  packages/host/app/components/operator-mode/delete-modal.gts
  packages/host/app/components/realm-dropdown.gts
  packages/host/app/resources/file.ts
  packages/host/app/services/card-service.ts
  packages/host/app/services/operator-mode-state-service.ts
  packages/host/app/services/realm-info-service.ts
  packages/host/app/services/recent-files-service.ts
  packages/host/package.json
  packages/host/tests/acceptance/code-submode/create-file-test.gts
  packages/host/tests/acceptance/code-submode/inspector-test.ts
  packages/host/tests/acceptance/code-submode/recent-files-test.ts
  packages/host/tests/integration/search-index-test.gts
  packages/host/tests/unit/convert-to-class-name-test.ts
  packages/host/tests/unit/realm-paths-test.ts
  packages/realm-server/tests/realm-server-test.ts
  packages/runtime-common/constants.ts
  packages/runtime-common/module-syntax.ts
  packages/runtime-common/package.json
  packages/runtime-common/paths.ts
  packages/runtime-common/realm.ts
  packages/runtime-common/router.ts
  pnpm-lock.yaml
Labels: bug

#1210 Auto attach with multiple stacks
  packages/host/app/components/ai-assistant/card-picker/index.gts
  packages/host/app/components/ai-assistant/card-picker/usage.gts
  packages/host/app/components/matrix/room.gts
  packages/host/app/resources/auto-attached-card.ts
  packages/host/app/services/operator-mode-state-service.ts
  packages/host/tests/cards/jersey.json
  packages/host/tests/cards/justin.json
  packages/matrix/helpers/index.ts
  packages/matrix/tests/messages.spec.ts
Labels: bug

#1207 Adding event card
  packages/ai-bot/tests/resources/chats/!EHSrJvmtuZtpNeKXsv:localhost.json
  packages/boxel-ui/addon/src/components.ts
  packages/drafts-realm/Event/1.json
  packages/drafts-realm/event.gts
Labels: card

#1215 matrix: Add setup failsafes
  packages/matrix/scripts/register-realm-users.sh
Labels: bug

#1214 ci: Update Actions dependencies to use Node 20
  .github/actions/init/action.yml
  .github/workflows/build-host.yml
  .github/workflows/ci.yaml
  .github/workflows/deploy-host.yml
  .github/workflows/deploy-motion.yml
  .github/workflows/deploy-ui.yml
  .github/workflows/pr-boxel-host.yml
  .github/workflows/pr-boxel-motion.yml
  .github/workflows/pr-boxel-ui.yml
  .github/workflows/sync-synapse-templates.yml
Labels: bug

#1206 common: Fix linting
  packages/runtime-common/package.json
  packages/runtime-common/tsconfig.json
  packages/runtime-common/types/index.d.ts
  pnpm-lock.yaml
Labels: bug, chore

#1229 Remove Waypoint configuration files
  packages/realm-server/waypoint.hcl
  packages/realm-server/waypoint.prod.hcl
Labels: bug

#1220 Fix debug command stuck in "Thinking..." state
  packages/ai-bot/README.md
  packages/ai-bot/main.ts
Labels: bug

#1252 host: Fix module hooks nesting
  packages/host/tests/acceptance/operator-mode-acceptance-test.gts
Labels: bug

#1260 ci: Update dorny/paths-filter to fix deprecation
  .github/workflows/ci.yaml
Labels: chore

#1272 Garden grid card champagne drinking
  packages/drafts-realm/GardenDesign/09d80848-5d60-4e69-9de1-66198c2e1eb9.json
  packages/drafts-realm/garden-design.gts
  packages/drafts-realm/package.json
  pnpm-lock.yaml
Labels: card

#1275 Add Goofy Switch to Carving Diagram
  packages/drafts-realm/CarvingTurnDiagram/f76cb2d0-eef5-4913-ade6-5a259d9e9f4e.json
  packages/drafts-realm/board-annotation.gts
  packages/drafts-realm/carving-turn-diagram.gts
  packages/drafts-realm/carving-turn-entry.json
Labels: card

#1265 base: Fix deployment sync to match other realms
  packages/realm-server/package.json
Labels: bug

#1276 Add AI generated D&D character sheet
  packages/drafts-realm/CharacterSheet/982ff843-2dfe-47fe-8be1-47221d5de933.json
  packages/drafts-realm/DnDItem/8ec1b337-1a53-479e-9bb8-3047e714142c.json
  packages/drafts-realm/InventoryItem/c7bf0673-77dc-49d7-a791-58c84be0cd6f.json
  packages/drafts-realm/Spell/5ed539c4-ab38-494f-bcdb-b2fc8ecc141a.json
  packages/drafts-realm/Spell/c8ebdcf6-b548-474f-bf12-ee6396b9bfbc.json
  packages/drafts-realm/Spell/d5858748-d81f-4e79-ba99-a4d62afa09c6.json
  packages/drafts-realm/dnd.gts
Labels: card

#1268 host: Add schema editor handling for empty file
  packages/host/app/components/operator-mode/syntax-error-display.gts
  packages/host/tests/acceptance/code-submode/schema-editor-test.ts
  packages/runtime-common/realm.ts
Labels: bug

#1287 common: Change SSE logging to debug level
  packages/runtime-common/realm.ts
Labels: enhancement

#1288 host: Add patch to silence slicing warnings
  package.json
  patches/ember-source@5.4.1.patch
  pnpm-lock.yaml
Labels: bug

#1293 host: Remove unused route
  packages/host/app/routes/code.ts
Labels: bug

#1305 Update ember-template-imports to 4.1.1
  package.json
  packages/boxel-motion/addon/package.json
  packages/boxel-motion/test-app/package.json
  packages/boxel-ui/addon/package.json
  packages/boxel-ui/test-app/package.json
  packages/boxel-ui/test-app/tests/integration/components/resizable-panel-group-test.gts
  packages/host/package.json
  pnpm-lock.yaml
Labels: chore

#1309 ui: Remove warning about missing panel values
  packages/boxel-ui/addon/src/components/resizable-panel-group/index.gts
Labels: bug

#1314 host: Change message editor to not capture scroll
  packages/host/app/components/matrix/room-message.gts
Labels: bug

#1318 host: Add wait for async assertion callback
  packages/host/tests/acceptance/code-submode/inspector-test.ts
Labels: bug
