Repository cardstack/boxel, pull requests merged in 2024-10, with the labels that each got.

#1619 Fix spacing in search box
  packages/boxel-ui/addon/src/components/input/index.gts
  packages/boxel-ui/addon/src/styles/variables.css
  packages/host/app/components/operator-mode/submode-layout.gts
  packages/host/app/components/search-sheet/index.gts
Labels: bug

#1632 ci: Remove unused change-check output
  .github/workflows/ci.yaml
Labels: chore

#1636 ci: Add more paths for Yaml lint workflow
  .github/workflows/ci-lint.yaml
  .github/workflows/yaml-lint.yml
Labels: chore

#1660 tools: Fix version commit determination
  .github/workflows/manual-vscode-boxel-tools.yml
Labels: bug

#1655 tools: Add file explorer autoopen
  packages/vscode-boxel-tools/src/extension.ts
Labels: enhancement

#1673 ci: Update Playwright to fix Matrix tests
  package.json
  packages/matrix/package.json
  pnpm-lock.yaml
Labels: bug, chore

#1705 tools: Remove workspace folders with logout
  packages/vscode-boxel-tools/src/extension.ts
Labels: bug

#1670 tools: Add file creation
  packages/vscode-boxel-tools/src/file-system-provider.ts
Labels: enhancement

#1697 tools: Fix accept headers and response-parsing
  packages/base/.realm.json
  packages/base/cards-grid.gts
  packages/base/default-templates/field-edit.gts
  packages/base/default-templates/isolated-and-edit.gts
  packages/base/field-component.gts
  packages/base/number.gts
  packages/boxel-ui/addon/src/components/field-container/index.gts
  packages/boxel-ui/addon/src/styles/variables.css
  packages/catalog-realm/.realm.json
  packages/experiments-realm/.realm.json
  packages/host/app/components/card-catalog/index.gts
  packages/host/app/components/card-catalog/modal.gts
  packages/host/app/components/card-prerender.gts
  packages/host/app/lib/utils.ts
  packages/host/config/schema/1728561353454_schema.sql
  packages/host/tests/acceptance/code-submode/create-file-test.gts
  packages/host/tests/acceptance/code-submode/file-tree-test.ts
  packages/host/tests/acceptance/code-submode/recent-files-test.ts
  packages/host/tests/acceptance/code-submode/schema-editor-test.ts
  packages/host/tests/acceptance/interact-submode-test.gts
  packages/host/tests/cards/.realm.json
  packages/host/tests/integration/components/card-basics-test.gts
  packages/host/tests/integration/components/card-copy-test.gts
  packages/host/tests/integration/components/card-def-field-def-relationships-test.gts
  packages/host/tests/integration/components/card-editor-test.gts
  packages/host/tests/integration/components/computed-test.gts
  packages/host/tests/integration/realm-indexing-and-querying-test.gts
  packages/host/tests/integration/realm-test.ts
  packages/matrix/tests/messages.spec.ts
  packages/matrix/tests/registration-with-token.spec.ts
  packages/realm-server/migrations/1728561353454_create-user-billing.js
  packages/realm-server/scripts/schema-dump.sh
  packages/realm-server/server.ts
  packages/runtime-common/index.ts
  packages/runtime-common/user-queries.ts
  packages/seed-realm/.realm.json
  packages/vscode-boxel-tools/README.md
  packages/vscode-boxel-tools/package.json
  packages/vscode-boxel-tools/src/extension.ts
  packages/vscode-boxel-tools/src/file-system-provider.ts
Labels: bug

#1708 tools: Update version to 0.0.21
  packages/vscode-boxel-tools/package.json
Labels: chore

#1703 tools: Fix problem matcher for watching
  .vscode/tasks.json
Labels: bug

#1713 ci: Add linting for seed realm
  .github/workflows/ci-lint.yaml
  packages/seed-realm/package.json
Labels: enhancement

#1714 tools: Fix labels and names
  packages/vscode-boxel-tools/README.md
  packages/vscode-boxel-tools/package.json
  packages/vscode-boxel-tools/src/diagnostics.ts
  packages/vscode-boxel-tools/src/extension.ts
  packages/vscode-boxel-tools/src/file-system-provider.ts
  packages/vscode-boxel-tools/src/synapse-auth-provider.ts
Labels: chore

#1712 matrix: Add link to registration success template
  .github/workflows/sync-synapse-templates.yml
  packages/matrix/docker/synapse/templates/registration_success.html
Labels: enhancement

#1733 host: Restore header workspace icons
  packages/boxel-ui/addon/src/components/realm-icon/index.gts
Labels: bug
