Repository cardstack/boxel, pull requests merged in 2024-07, with the labels that each got.

#1394 realm: Remove noise in tests
  packages/realm-server/package.json
Labels: bug

#1398 host: Add wrapping in assistant responses
  packages/host/app/components/ai-assistant/message/index.gts
  packages/host/tests/integration/components/ai-assistant-panel-test.gts
Labels: bug

#1400 host: Fix room name leakage between user sessions
  packages/host/app/services/matrix-service.ts
  packages/matrix/helpers/index.ts
  packages/matrix/tests/room-creation.spec.ts
Labels: bug

#1405 ci: Add Matrix trace uploads
  .github/workflows/ci.yaml
Labels: enhancement

#1399 host: Change test to use extracted storage key
  packages/host/tests/integration/components/ai-assistant-panel-test.gts
Labels: bug

#1404 host: Update assistant panel loading state
  packages/host/app/components/ai-assistant/panel.gts
  packages/matrix/tests/room-creation.spec.ts
Labels: enhancement

#1417 host: Fix appearance of username uniqueness checkmark
  packages/boxel-ui/addon/src/components/input-group/index.gts
  packages/boxel-ui/addon/src/components/input-group/usage.gts
  packages/boxel-ui/test-app/tests/integration/components/input-group-test.gts
  packages/host/app/components/matrix/register-user.gts
Labels: bug

#1422 host: Add test fixes for Firefox
  packages/host/tests/acceptance/code-submode/editor-test.ts
  packages/host/tests/helpers/index.gts
  packages/host/tests/integration/components/operator-mode-test.gts
Labels: bug

#1430 Update @embroider/addon-dev and Rollup
  packages/boxel-motion/addon/package.json
  packages/boxel-ui/addon/package.json
  pnpm-lock.yaml
Labels: chore

#1443 host: Fix read receipt errors
  packages/host/app/components/matrix/room-message.gts
  packages/host/tests/integration/components/ai-assistant-panel-test.gts
Labels: bug

#1438 ci: Add host previews on changes to boxel-ui
  .github/workflows/pr-boxel-host.yml
Labels: enhancement

#1431 Fix pnpm install noise
  package.json
  packages/ai-bot/tsconfig.json
  packages/boxel-motion/addon/babel.config.json
  packages/boxel-motion/addon/package.json
  packages/boxel-motion/test-app/package.json
  packages/boxel-ui/addon/babel.config.json
  packages/boxel-ui/addon/package.json
  packages/boxel-ui/test-app/package.json
  packages/host/package.json
  packages/host/tsconfig.json
  packages/realm-server/package.json
  packages/realm-server/tsconfig.json
  packages/runtime-common/etc/test-fixtures.ts
  packages/runtime-common/global.d.ts
  packages/runtime-common/package.json
  packages/runtime-common/transpile.ts
  pnpm-lock.yaml
  vendor/ember-template-imports/package.json
Labels: bug

#1453 host: Update to ember-window-mock v1.0.1
  package.json
  packages/host/package.json
  patches/ember-window-mock@1.0.0.patch
  pnpm-lock.yaml
Labels: chore

#1451 realm: Fix typo in staging realm server startup
  packages/realm-server/scripts/start-staging.sh
Labels: bug

#1456 Fix bug where auto-attachment resource errors when new topmost card is saving
  packages/host/app/resources/auto-attached-card.ts
  packages/host/app/resources/search.ts
  packages/host/tests/acceptance/interact-submode-test.gts
Labels: bug

#1450 Move production deployment targets to boxel.ai
  .github/workflows/build-host.yml
  .github/workflows/deploy-host.yml
  .github/workflows/pr-boxel-host.yml
  packages/realm-server/scripts/start-production.sh
Labels: chore
