Repository cardstack/boxel, pull requests merged in 2024-06, with the labels that each got.

#1236 Get card to update while chess pieces move
  packages/drafts-realm/Chess/c09f9bb3-df3f-4337-a6bd-cc4c96a5caa3.json
  packages/drafts-realm/chess.gts
Labels: card

#1316 ci: Add test splitting for host
  .github/workflows/ci.yaml
  packages/host/package.json
  packages/host/testem.js
  packages/host/tests/test-helper.js
  pnpm-lock.yaml
Labels: chore

#1241 drafts: Add LeafletMap and LeafletGtfs
  packages/base/field-component.gts
  packages/drafts-realm/LeafletGtfs/belgrade.json
  packages/drafts-realm/LeafletGtfs/cairo.json
  packages/drafts-realm/LeafletGtfs/nyc-ferries.json
  packages/drafts-realm/LeafletGtfs/saint-louis.json
  packages/drafts-realm/LeafletGtfs/winnipeg.json
  packages/drafts-realm/LeafletMap/winnipeg.json
  packages/drafts-realm/leaflet-gtfs.gts
  packages/drafts-realm/leaflet-map.gts
Labels: card

#1326 host: Restore recent files background
  packages/host/app/components/operator-mode/code-submode.gts
Labels: bug

#1325 host: Add waits to fix Percy flapping
  packages/host/tests/integration/components/operator-mode-test.gts
Labels: bug

#1324 host: Add truncation for code mode URL field
  packages/host/app/components/operator-mode/card-url-bar.gts
Labels: enhancement

#1333 ci: Fix Percy on host test reruns
  .github/workflows/ci-host.yaml
  .github/workflows/ci-lint.yaml
  .github/workflows/ci.yaml
Labels: bug

#1345 host: Update operator mode assertion for subsets
  packages/host/tests/acceptance/code-submode/inspector-test.ts
  packages/host/tests/acceptance/interact-submode-test.gts
  packages/host/tests/acceptance/operator-mode-acceptance-test.gts
  packages/host/tests/helpers/operator-mode-parameters-match.ts
Labels: enhancement

#1355 ui: Update ResizablePanelGroup internals
  packages/boxel-ui/addon/package.json
  packages/boxel-ui/addon/src/components.ts
  packages/boxel-ui/addon/src/components/resizable-panel-group/handle.gts
  packages/boxel-ui/addon/src/components/resizable-panel-group/index.gts
  packages/boxel-ui/addon/src/components/resizable-panel-group/panel.gts
  packages/boxel-ui/addon/src/components/resizable-panel-group/resize-handler.gts
  packages/boxel-ui/addon/src/components/resizable-panel-group/usage.gts
  packages/boxel-ui/addon/src/types/ember-ref-bucket/index.d.ts
  packages/boxel-ui/test-app/tests/integration/components/resizable-panel-group-test.gts
  packages/host/app/components/ai-assistant/panel.gts
  packages/host/app/components/operator-mode/code-submode.gts
  packages/host/app/components/operator-mode/submode-layout.gts
  pnpm-lock.yaml
Labels: chore

#1380 ci: Move ai-bot deployment alongside boxel
  .github/workflows/ci.yaml
  .github/workflows/manual-ai-bot.yml
  .github/workflows/manual-deploy.yml
Labels: enhancement
