Repository cardstack/boxel, pull requests merged in 2025-05, with the labels that each got.

#2544 host: Fix bot patching when search block empty
  packages/host/app/commands/apply-search-replace-block.ts
  packages/host/app/components/ai-assistant/code-block.gts
  packages/host/tests/integration/components/ai-assistant-panel/codeblocks-test.gts
Labels: bug

#2546 host: Extract HtmlGroupCodeBlock
  packages/host/app/components/ai-assistant/formatted-message.gts
Labels: optimization

#2547 ci: Restore inline realm server logging
  .github/workflows/ci-host.yaml
  .github/workflows/ci.yaml
Labels: enhancement

#2567 Fix path for content-tag in deployed environments
  packages/realm-server/server.ts
Labels: bug

#2575 host: Extract code mode ModuleInspector
  packages/host/app/components/card-renderer.gts
  packages/host/app/components/matrix/room-message-command.gts
  packages/host/app/components/operator-mode/card-renderer-panel/embedded-preview.gts
  packages/host/app/components/operator-mode/card-renderer-panel/fitted-format-gallery.gts
  packages/host/app/components/operator-mode/card-renderer-panel/index.gts
  packages/host/app/components/operator-mode/code-submode.gts
  packages/host/app/components/operator-mode/code-submode/module-inspector.gts
  packages/host/app/components/operator-mode/code-submode/playground/field-chooser-modal.gts
  packages/host/app/components/operator-mode/code-submode/playground/instance-chooser-dropdown.gts
  packages/host/app/components/operator-mode/code-submode/playground/playground-preview.gts
  packages/host/app/components/operator-mode/code-submode/spec-preview.gts
  packages/host/app/components/operator-mode/stack-item.gts
  packages/host/app/components/search-sheet/results-section.gts
  packages/host/tests/acceptance/code-submode-test.ts
  packages/host/tests/acceptance/code-submode/card-playground-test.gts
  packages/host/tests/acceptance/code-submode/create-file-test.gts
  packages/host/tests/acceptance/code-submode/editor-test.ts
  packages/host/tests/acceptance/code-submode/inspector-test.ts
  packages/host/tests/acceptance/code-submode/schema-editor-test.ts
  packages/host/tests/integration/components/preview-test.gts
Labels: chore

#2599 host: Remove flaky catalog “Use” test
  packages/host/tests/acceptance/catalog-app-test.gts
Labels: bug

#2631 ui: Change select icon to invert on vertical above
  packages/boxel-ui/addon/src/components/select/index.gts
  packages/boxel-ui/addon/src/components/select/trigger.gts
Labels: enhancement

#2649 Fix card creation NOT returning in pre-rendered search for apps
  packages/base/card-api.gts
  packages/catalog-realm-dev/blog-app/components/card-list.gts
  packages/catalog-realm-dev/catalog-app/components/grid.gts
  packages/catalog-realm-dev/crm-app/app-card.gts
  packages/catalog-realm-dev/crm-app/components/card-list.gts
  packages/experiments-realm/app-card.gts
  packages/experiments-realm/blog-app.gts
  packages/experiments-realm/components/card-list.gts
  packages/experiments-realm/components/grid.gts
  packages/experiments-realm/crm-app.gts
  packages/host/app/components/card-catalog/index.gts
  packages/host/app/components/operator-mode/code-submode/playground/instance-chooser-dropdown.gts
  packages/host/app/components/operator-mode/code-submode/playground/playground-panel.gts
  packages/host/app/components/operator-mode/code-submode/playground/playground-title.gts
  packages/host/app/components/prerendered-card-search.gts
  packages/realm-server/tests/cards/person-with-error.gts
  packages/runtime-common/index.ts
  packages/runtime-common/package.json
  packages/runtime-common/prerendered-card-search.ts
  packages/seed-realm/app-card.gts
  packages/seed-realm/blog-app.gts
  packages/seed-realm/components/card-list.gts
  packages/seed-realm/components/grid.gts
  packages/seed-realm/crm-app.gts
  pnpm-lock.yaml
Labels: bug
